### ISSUE TITLE
Status Bar Theme inconsistent

### ISSUE THREAD

**Issue by patkellydesigns** [patkellydesigns/trump_machine#1]
The status bar is Light on some screens and dark on others.

**Comment by ThalapathySiva** [comment]
Shall I work on this issue? Can you assign me?

**Comment by ThalapathySiva** [comment]
* Error running Gradle:
ProcessException: Process "F:\trump_machine\android\gradlew.bat" exited abnormally:

  Command: F:\trump_machine\android\gradlew.bat app:properties

Please review your Gradle project setup in the android/ folder.


If run the app I am getting above error

**Comment by patkellydesigns** [comment]
It's light on the home screen and dark on the rest. Have a look at it and let me know what you think. I think light looks best.

**Comment by patkellydesigns** [comment]
I changed some things in Gradle when I released it let me clean it up and push. @ThalapathySiva

**Comment by ThalapathySiva** [comment]
Yeah Sure lemme know when its pushed. Even I think Light is best for all.

**Comment by patkellydesigns** [comment]
I updated the Gradle so that it will (hopefully) build with a debug key for you. 
let me know. if you can get it to run.

**Comment by ThalapathySiva** [comment]
Did you pushed I cant see the changes in your repo!

**Comment by ThalapathySiva** [comment]
Now working fine which colour do you want in status bar?

**Comment by patkellydesigns** [comment]
I think light works best.

**Comment by patkellydesigns** [comment]
Thank you for your contribution. The app is live on the Play Store I will add you as a Contributor.

Feel free to add it to your portfolio/.

**Comment by ThalapathySiva** [comment]
sure thanks.!

**Comment by patkellydesigns** [comment]
@all-contributors please add @ThalapathySiva  for infrastructure, tests, and code

**Comment by patkellydesigns** [comment]
@all-contributors please add @Warimp  for infrastructure, tests, project management and code
