### ISSUE TITLE
Comment out Share feature until we implement a full share feature

### ISSUE THREAD

**Issue by patkellydesigns** [patkellydesigns/trump_machine#4]
Currently, the share button will only copy and share the text.

https://pub.dev/packages/share

This package might be a good building block but I think there is probably a better package. 

I want to Tweet, Instagram or Facebook. with a #TrumpMachine Hashtag and a link to the Playstore app.

**Comment by ThalapathySiva** [comment]
Share option need to be removed? Shall I work on this..

**Comment by patkellydesigns** [comment]
@ThalapathySiva lets break this into 3 issues that are easy to implement.

Here is where my thinking is on this project right now.

Currently, the ListTile expands and shows a heart for adding to the favorites list which we are not persisting #3 https://github.com/patkellydesigns/trump_machine/issues/3#issue-510709645. 

I will assign myself this right now. I plan on using Hive so I can learn to use it. 
https://pub.dev/packages/hive

Moving forward from a UI perspective we should design a nice quote card to use instead of a ListTile(). 
#8 

The other issue is that this share package function uses this.  

> A Flutter plugin to share content from your Flutter app via the platform's share dialog.

Wraps the ACTION_SEND Intent on Android and UIActivityViewController on iOS.

Currently, this just shares and ugly String and provides no real value. I feel like sharing to social media should include a link to the Playstore Store a popular Trump Hashtag and 

This code currently only shares a plain text String which is the Quote

When we press button we run this function

 `Share.share(quoteText);`

I want to pass in something like this 

`Share.share(quoteText,  hashtag, playstoreLink, appIcon)`
 
After reading through the docs I noticed the Share() constructor takes a Map of parameters and will be easy to modify. 

I think we should proceed with making it share properly.

**Comment by patkellydesigns** [comment]
Just needs to be commented out for now.

**Comment by patkellydesigns** [comment]
@all-contributors please add @patkellydesigns  for infrastructure, tests, and code
